"""empty message

Revision ID: 0853e8b1872d
Revises: 506e3ad9389d
Create Date: 2016-11-06 12:46:01.078917

"""

# revision identifiers, used by Alembic.
revision = '0853e8b1872d'
down_revision = '506e3ad9389d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('compURL', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'compURL')
    ### end Alembic commands ###
