"""empty message

Revision ID: 506e3ad9389d
Revises: 2123dd688c73
Create Date: 2016-11-06 09:24:06.078603

"""

# revision identifiers, used by Alembic.
revision = '506e3ad9389d'
down_revision = '2123dd688c73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyShortName', sa.String(length=40), nullable=True),
    sa.Column('companyFullName', sa.String(length=128), nullable=True),
    sa.Column('financeStage', sa.String(length=60), nullable=True),
    sa.Column('workYear', sa.String(length=60), nullable=True),
    sa.Column('createTime', sa.String(length=60), nullable=True),
    sa.Column('positionLables', sa.String(length=60), nullable=True),
    sa.Column('salary', sa.String(length=40), nullable=True),
    sa.Column('businessZones', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('positionName', sa.String(length=60), nullable=True),
    sa.Column('district', sa.String(length=60), nullable=True),
    sa.Column('companyLabelList', sa.String(length=120), nullable=True),
    sa.Column('positionAdvantage', sa.String(length=120), nullable=True),
    sa.Column('jobNature', sa.String(length=60), nullable=True),
    sa.Column('companySize', sa.String(length=60), nullable=True),
    sa.Column('industryField', sa.String(length=60), nullable=True),
    sa.Column('formatCreateTime', sa.String(length=60), nullable=True),
    sa.Column('education', sa.String(length=60), nullable=True),
    sa.Column('companyLogo', sa.String(length=120), nullable=True),
    sa.Column('positionId', sa.String(length=60), nullable=True),
    sa.Column('addr', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jobs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task', sa.VARCHAR(), nullable=True),
    sa.Column('created_time', sa.INTEGER(), nullable=True),
    sa.Column('updated_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job')
    ### end Alembic commands ###
